### ISSUE TITLE
Góp ý cho thư viện cgraph_vector

### ISSUE THREAD

**Issue by hectorsudo** [bangoc/cgraph#2]
Thưa thầy,
Em có một số góp ý cho thư viện cgraph_vector như sau:

1. Ở các hàm trong thư viện này, em nghĩ mình nên sử dụng con trỏ tới vector làm tham số (tức là 1 function sẽ có dạng là `cgraph_ivec_function(cgraph_ivec_t *vec)`). Còn với các hàm không thay đổi kích thước, nội dung (như `size()`, `capacity()`, ...) thì sẽ đặt `const` ở trước. Làm như vậy sẽ tiết kiệm bộ nhớ hơn rất nhiều.

2. Ở hàm `cgraph_ivec_setsize()` hiện tại, trong trường hợp `newsize > capacity`, hàm sẽ không cho phép mình tăng size của vector lên thành `newsize`. Nên em nghĩ mình nên dùng hàm `cgraph_ivec_grow(v, newsize)` trước để tăng capacity của vector, rồi mới dùng `cvector_set_size()`. 

3. Em thử copy vector `b` từ 1 vector `a` đã có từ trước bằng toán tử `=`. Vì dùng toán tử `=` nên cả `a và b` đều trỏ đến cùng 1 memory block, nên khi thay đổi 1 giá trị của `a` thì `b` cũng thay đổi theo (đáng lẽ `b` vẫn phải giữ nguyên). Vì thế, em nghĩ nên có 1 hàm `cgraph_ivec_copy()` để giải quyết vấn đề này ạ.

**Comment by bangoc** [comment]
Trước tiên cám ơn em vì các góp ý.
Thầy trả lời như sau:
1. Nhận xét 1 của em hợp lý, thầy cũng đang áp dụng quy tắc này, các API cho cgraph_ivec_t hiện đã thỏa mãn yêu cầu này.
2. capacity là số chỗ đã cấp phát, size là số chỗ đã sử dụng. Theo logic nếu setsize với size > capacity thì nhận định đó là lỗi thì phù hợp hơn là đáp ứng. Hai tham số size và capacity mỗi cái vốn có nghĩa riêng, vì vậy sẽ không grow bên trong setsize.
3. phép gán trong C đúng là như vậy. Trong các triển khai hiện tại chưa cần đến thao tác copy một vec-tơ, vì vậy thầy chưa đưa hàm đó vào. Khi nào phát sinh nhu cầu thì sẽ bổ xung, có thể là copy hoặc clone.

**Comment by hectorsudo** [comment]
Em đã hiểu vấn đề 2 và 3.

Với vấn đề thứ nhất, em thấy còn một số hàm chưa sử dụng con trỏ làm tham số như `cgraph_ivec_max(), cgraph_ivec_isininterval(), cgraph_ivec_order(), cgraph_ivec_null(), cgraph_ivec_setsize(), cgraph_ivec_capacity(), cgraph_ivec_size()`. Thầy có thể cân nhắc chỉnh sửa để đồng bộ với các hàm khác được không ạ?

**Comment by bangoc** [comment]
Em muốn dùng con trỏ ở khắp nơi à?

**Comment by hectorsudo** [comment]
Dạ vâng ạ. Em nghĩ nó sẽ tiết kiệm bộ nhớ hơn ạ. Với cả làm như thế sẽ tránh được những trường hợp nhầm lẫn khi gọi hàm. Ví dụ như `cgraph_ivec_push_back(&vec) rồi gọi cgraph_ivec_size(&vec)` sẽ đỡ gây nhầm lẫn hơn so với   `cgraph_ivec_push_back(&vec) rồi gọi cgraph_ivec_size(vec)`

**Comment by bangoc** [comment]
Như bây giờ thì &vec không tương thích kiểu cho cgraph_ivec_size, cái này gọi là an toàn dựa trên kiểu dữ liệu, nhỡ nhầm một tí thì trình biên dịch vẫn có thông báo đó chứ.
Tiết kiệm bộ nhớ hơn thì không đúng: Không khó để tìm ra bản chất cgraph_ivec_t là int32_t *, như vậy cgraph_ivec_t * sẽ là int32_t **, đều cỡ 8 bytes thì tiết kiệm bộ nhớ gì ở đây đâu.
Về nhận xét 1 ý thầy là phát hiện những cái bất biến đúng bản chất rồi thêm const vào là tốt, nên làm. Còn chuyển tất cả các gọi hàm về định dạng foo(&vec) không phải ý hay.
Quan trọng nhất là thầy tin vào sự xuất sắc của em và các bạn, hiểu rõ câu lệnh, những cái mình viết và biết mình đang muốn làm gì thì đơn giản thôi nhỉ.

**Comment by hectorsudo** [comment]
Dạ vâng em cảm ơn thầy, em hiểu rồi ạ. Em xin phép đóng issue này ở đây ạ.
