### ISSUE TITLE
Bug ở cgraph_vector

### ISSUE THREAD

**Issue by hectorsudo** [bangoc/cgraph#4]
Thưa thầy,

Em phát hiện 1 bug trong file `cgraph_vector.c`. Hàm `cgraph_ivec_order()` chưa chứa dòng `return 0`. Khi không return thì tất cả các test liên quan đến giao diện cgraph như `neighbors, incident, create_graph, bfs, ...` đều bị fail (một số máy có thể vẫn hoạt động bình thường, một số máy sẽ bị lỗi như máy của em).

Mong thầy kiểm tra và sửa sớm nhất có thể ạ.

Em cảm ơn.

**Comment by bangoc** [comment]
Em phát hiện vấn đề đúng chỗ đấy, hiện tại hàm cgraph_ivec_order chưa trả về giá trị.
Tình trạng xử lý lỗi hiện vẫn đang ở mức rất thô sơ: các hàm trả về giá trị kiểu int, 0 - mọi thứ Ok, khác 0 là có lỗi.
Em tự sửa rồi tạo pull request thầy xem nhé.

**Comment by hectorsudo** [comment]
Dạ vâng, em đã tạo pull request #5 rồi ạ.
Hiện chỉ có mỗi hàm `cgraph_ivec_order()` là thiếu `return`, còn các hàm còn lại đều đúng hết ạ.

**Comment by bangoc** [comment]
Đã Merge rồi nhé,
thầy cũng bổ xung thêm -Werror=return-type, 
trình biên dịch sẽ bắt những lỗi kiểu như thế cho triệt để.
